site_name: Pierre Kancir personal blog
site_url: https://khancyr.github.io
theme:
  language: en
  name: material
  favicon: images/Hivebotics-blue.svg
  logo: images/favicon-32x32.png

  features:
    - navigation.instant
    - search.suggest
  palette:
    scheme: slate
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - js/goatcounter.js

plugins:
  - blog:
      blog_toc: true
      archive_date_format: MMMM yyyy
  - search
  - social:
      cards_layout_options:
        background_color: "#2d4f6c"
  - tags
  - rss:
      enabled: !ENV [CI, false]
      match_path: blog/posts/.*
      date_from_meta:
        as_creation: date.created
        as_update: date.updated
      categories:
        - categories
        - tags



extra:
  social:
    - icon: fontawesome/brands/linkedin
      name: Pierre on LinkedIn
      link: https://www.linkedin.com/in/pierre-kancir/
    - icon: fontawesome/brands/github
      name: Pierre on Github
      link: https://github.com/khancyr
    - icon: fontawesome/solid/rss
      name: Pierre's blog on RSS
      link: https://khancyr.github.io/feed_rss_created.xml

copyright: Copyright &copy; 2016 - 2025 Pierre Kancir