# A post with an `image:` (absolute URL) uses it as its link preview instead of
# the card generated by Material's social plugin, which has no per-page opt-out.
def on_page_context(context, page, config, nav):
    image = page.meta.get("image")
    if not image:
        return
    # drop og:image:type/width/height, they describe the generated card
    tags = [t for t in page.meta.get("meta", []) if not t.get("property", "").startswith("og:image:")]
    for t in tags:
        if t.get("property") == "og:image" or t.get("name") == "twitter:image":
            t["content"] = image
    page.meta["meta"] = tags
